### ISSUE TITLE
[Proposal] "import/no-extraneous-dependencies": ["error", {"devDependencies": false, "optionalDependencies": false}]

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol-base#12]

**Comment by tw0517tw** [comment]
> devDependencies: If set to false, then the rule will show an error when devDependencies are imported.
但我們蠻常 import dev dependencies 的吧

**Comment by chentsulin** [comment]
這條目前也是打開
在特定檔案 disable 就好
