### ISSUE TITLE
[Proposal] linebreak-style: 'off'

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/eslint-config-yoctol-base#25]
我們專案常常(好、只有我QQ)跨平台
而 git 就有處理這件事情，我 commit 的都會自動轉換成 unix 形式，
所以我覺得這個可以關掉

https://github.com/airbnb/javascript/blob/ca1124cd8d2e33addbffb3b1743849e2bf774039/packages/eslint-config-airbnb-base/CHANGELOG.md#500--2016-07-24

**Comment by chentsulin** [comment]
沒關掉在 windows 會 error?

**Comment by tw0517tw** [comment]
我的 git 設定 checkout 轉換 windows，commit 轉換 unix，所以我本機上的 code 都是 windows 格式換行，
一次會噴幾千個 error

**Comment by chentsulin** [comment]
http://eslint.org/docs/rules/linebreak-style
我 ok 
其他人呢 @zeldalink0515 @kpman @stegben

**Comment by kpman** [comment]
我 ok 
那之前都怎麼處理呀？

**Comment by tw0517tw** [comment]
`npm run testonly`

**Comment by zeldalink0515** [comment]
我 OK

**Comment by chentsulin** [comment]
@tw0517tw 直接發個 PR?
