### ISSUE TITLE
[Proposal] no-unused-expressions: 0 (best-practices.js)

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol-base#5]
In tests, it's helpful when writing some assertions

**Comment by tw0517tw** [comment]
有辦法用某種路徑檢查的方式讓他只改 test 資料夾裡面的 rule 嗎?

**Comment by chentsulin** [comment]
目前不知道有這種方法，剛剛看了一下自己寫 rule 目前只看到有 
`getFilename() - returns the filename associated with the source.`
http://eslint.org/docs/developer-guide/working-with-rules

**Comment by tw0517tw** [comment]
或是 copy 原本的 rule 然後改成遇到 expect 就不執行之類的

**Comment by chentsulin** [comment]
喔喔 可以 不過這就像了解 babel 一樣要去處理 AST

**Comment by tw0517tw** [comment]
參考資料
https://github.com/eslint/eslint/issues/2102

**Comment by chentsulin** [comment]
dirty-chai 我之前有看到過，但當時覺得為了這樣不用原生語法而多加一個 lib 不確定是不是好事
https://github.com/prodatakey/dirty-chai

**Comment by chentsulin** [comment]
還是我們就用 dirty-chai 看那討論串大家這麼支持

**Comment by tw0517tw** [comment]
也行

**Comment by chentsulin** [comment]
禮拜一過後來改

**Comment by chentsulin** [comment]
using dirty-chai
