### ISSUE TITLE
[Proposal] eslint-plugin-import/order

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol-base#8]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

**Comment by tw0517tw** [comment]
這個是不同 module 類型之間的排序 (內建先，再來 external，等等)，有點像 PEP8 裡面那種
但還沒有處理到同類型之間的排序

加上去也是有點幫助

**Comment by chentsulin** [comment]
同類的順序我不太在意

**Comment by chentsulin** [comment]
我們用 
```js
import/order: ["error", {"newlines-between": "never"}]
```
這樣嗎？
@tw0517tw @kpman @zeldalink0515 @stegben

**Comment by tw0517tw** [comment]
我有時候會想要換行 我覺得不用設定 newlines-between

**Comment by chentsulin** [comment]
其實有這規則 只是沒有 enable
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L108

**Comment by tw0517tw** [comment]
看到 `'import/newline-after-import'` 好像也可以打開

**Comment by chentsulin** [comment]
但我覺得固定比較好？

**Comment by tw0517tw** [comment]
那我偏好 always

**Comment by chentsulin** [comment]
下面是 airbnb 的設定

```js
'import/order': ['off', {
    groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
    'newlines-between': 'never',
}],
```

打開之外有什麼共識了嗎？ @kpman @zeldalink0515 @tw0517tw @Destinia

**Comment by tw0517tw** [comment]
排序 ok
newlines between 一樣希望 always

**Comment by kpman** [comment]
排序 ok，有沒有空行我都可以
