### ISSUE TITLE
[Proposal] import/newline-after-import: 2

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol-base#9]

**Comment by tw0517tw** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/newline-after-import.md

When Not To Use It
If you like to visually group module imports with its usage, you don't want to use this rule.

我們會常遇到這個狀況嗎

**Comment by chentsulin** [comment]
不會

**Comment by kpman** [comment]
newline-after-import 我覺得要打開

**Comment by chentsulin** [comment]
Airbnb 已打開
https://github.com/airbnb/javascript/blob/eslint-config-airbnb-base-v5.0.3/packages/eslint-config-airbnb-base/rules/imports.js#L123
